version: '3'

services:
  db:
    image: mysql:8.0
    container_name: db_customer_care
    volumes:
      - ./db/initdb/:/docker-entrypoint-initdb.d
      - ./db/data/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "9906:3306"
  web:
    build: .
    image: php:7.2.2-apache
    container_name: custemer_care
    depends_on:
      - db
    volumes:
      - ./tot_customer_cat/:/var/www/html/tot_customer_cat
    environment:
      DEV: production
      MYSQL_HOST: ${DB_HOST}
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PW}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "8001:80"
    stdin_open: true
    tty: true